INSERT INTO category_translation(id, name, language, translation) VALUES (1,'Animais','pt','Animais');
INSERT INTO category_translation(id, name, language, translation) VALUES (2,'Animais','en','Animals');
INSERT INTO category_translation(id, name, language, translation) VALUES (3,'Cinema','pt','Cinema');
INSERT INTO category_translation(id, name, language, translation) VALUES (4,'Cinema','en','Cinema');
INSERT INTO category_translation(id, name, language, translation) VALUES (5,'Comida','pt','Comida');
INSERT INTO category_translation(id, name, language, translation) VALUES (6,'Comida','en','Food');
INSERT INTO category_translation(id, name, language, translation) VALUES (7,'Desportos','pt','Desportos');
INSERT INTO category_translation(id, name, language, translation) VALUES (8,'Desportos','en','Sports');
INSERT INTO category_translation(id, name, language, translation) VALUES (9,'Empregos','pt','Empregos');
INSERT INTO category_translation(id, name, language, translation) VALUES (10,'Empregos','en','Jobs');
INSERT INTO category_translation(id, name, language, translation) VALUES (11,'Férias','pt','Férias');
INSERT INTO category_translation(id, name, language, translation) VALUES (12,'Férias','en','Vacations');
INSERT INTO category_translation(id, name, language, translation) VALUES (13,'Hábitos','pt','Hábitos');
INSERT INTO category_translation(id, name, language, translation) VALUES (14,'Hábitos','en','Habits');
INSERT INTO category_translation(id, name, language, translation) VALUES (15,'Locais','pt','Locais');
INSERT INTO category_translation(id, name, language, translation) VALUES (16,'Locais','en','Places');
INSERT INTO category_translation(id, name, language, translation) VALUES (17,'Música','pt','Música');
INSERT INTO category_translation(id, name, language, translation) VALUES (18,'Música','en','Music');
INSERT INTO category_translation(id, name, language, translation) VALUES (19,'Natureza','pt','Natureza');
INSERT INTO category_translation(id, name, language, translation) VALUES (20,'Natureza','en','Nature');
INSERT INTO category_translation(id, name, language, translation) VALUES (21,'Objetos','pt','Objetos');
INSERT INTO category_translation(id, name, language, translation) VALUES (22,'Objetos','en','Objects');
INSERT INTO category_translation(id, name, language, translation) VALUES (23,'Passatempos','pt','Passatempos');
INSERT INTO category_translation(id, name, language, translation) VALUES (24,'Passatempos','en','Hobbies');
INSERT INTO category_translation(id, name, language, translation) VALUES (25,'Pessoas','pt','Pessoas');
INSERT INTO category_translation(id, name, language, translation) VALUES (26,'Pessoas','en','People');
INSERT INTO category_translation(id, name, language, translation) VALUES (27,'Veículos','pt','Veículos');
INSERT INTO category_translation(id, name, language, translation) VALUES (28,'Veículos','en','Vehicles');
INSERT INTO category_translation(id, name, language, translation) VALUES (29,'Outra','pt','Outra');
INSERT INTO category_translation(id, name, language, translation) VALUES (30,'Outra','en','Other');

INSERT INTO category(id, name, image_number) VALUES (1,'Animais',0);
INSERT INTO category(id, name, image_number) VALUES (2,'Cinema',0);
INSERT INTO category(id, name, image_number) VALUES (3,'Comida',0);
INSERT INTO category(id, name, image_number) VALUES (4,'Desportos',0);
INSERT INTO category(id, name, image_number) VALUES (5,'Empregos',0);
INSERT INTO category(id, name, image_number) VALUES (6,'Férias',0);
INSERT INTO category(id, name, image_number) VALUES (7,'Hábitos',0);
INSERT INTO category(id, name, image_number) VALUES (8,'Locais',0);
INSERT INTO category(id, name, image_number) VALUES (9,'Música',0);
INSERT INTO category(id, name, image_number) VALUES (10,'Natureza',0);
INSERT INTO category(id, name, image_number) VALUES (11,'Objetos',0);
INSERT INTO category(id, name, image_number) VALUES (12,'Passatempos',0);
INSERT INTO category(id, name, image_number) VALUES (13,'Pessoas',0);
INSERT INTO category(id, name, image_number) VALUES (14,'Veículos',0);
INSERT INTO category(id, name, image_number) VALUES (15,'Outra',0);